### PR TITLE
SLING-7346: handle JSONResponse properties as json if possible.

### PR DESCRIPTION
**Pull request by karlpauls**
@bhardwajrahul20 I reworked your patch a little and tried to work in some of suggestions by @kwin.

The main idea is to fail fast when a property is set we can't translate into json and only allow such values (i.e., it is either of type {String, Boolean, Number, null} or the toString() is parseable as json). 

Furthermore, I added some javadoc to make this explicit.

@cziegeler and @rombert - what do you think?

### CODE REVIEW

**Comment by karlpauls** [comment]
I forgot to remove the copy of the JsonTicksParser - its embedded directly from the contentparser now. @rombert does this look like the way to go?

**Comment by rombert** [comment]
This basically looks ok to me. My only slight worry is that the JsonReponse may be used as an implementation of the PostResponse interface and such exceptions may be opaque. On the other hand, setting invalid JSON as property values would be leading to problems anyway so we just report the problem earlier.

**Comment by npeltier** [comment]
@karlpauls @rombert are we considering at some point to have json parsing and building central facilities?

**Comment by rombert** [comment]
@npeltier  - we currently use http://johnzon.apache.org/ for JSON. What exactly did you have in mind?

**Pull request merged**
